config/routes.rb
Rails.application.routes.draw do
  get 'send/index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  resources :todo_lists do
    resources :todo_tasks do
      member do
       patch :complete
      end
    end
  end
  get 'send' => 'send#index'
  post 'send' => 'send#create'
  devise_for :users
  root to: "todo_lists#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  belongs_to :user
  has_many :todo_tasks

  def self.all_todo_list_task
    TodoList.left_joins(:todo_tasks).select("todo_lists.*, todo_tasks.content as task").where(
      "todo_lists.id > 0 OR
      todo_tasks.todo_list_id = todo_lists.id")
  end

  def self.all_todo_list
    TodoList.all
  end
  def self.to_csv
    CSV.generate do |csv|
      columns = %w(id title description task)
      csv << columns.map(&:humanize)
      all_todo_list_task.each do |student|
        csv << student.attributes.values_at(*columns)
      end
    end
 end

end

app/models/todo_task.rb
class TodoTask < ApplicationRecord
  belongs_to :todo_list

  def completed?
   !completed_at.blank?
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_attached_file :avatar, styles: { medium: "300x300", thumb: "100x100" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  has_many :todo_lists
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :authentication_keys => [:username]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
   added_attrs = [:username, :email, :password, :password_confirmation, :current_password , :avatar]
   devise_parameter_sanitizer.permit :sign_up, keys: [:username, :email, :password, :password_confirmation, :avatar, :avatar_cache]
   devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new]

  def index
  end

  def new
end
end

app/controllers/send_controller.rb
class SendController < ApplicationController

  def index
  end

  def create
   @params= params
   ContactMailer.contact_send(params).deliver
   flash[:notice]= "mensaje enviado"
   redirect_to send_path
  end

end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :new]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = current_user.todo_lists
    respond_to do |format|
     format.html
     format.csv { send_data @todo_lists.to_csv, filename: "lists-#{Date.today}.csv" }
     format.pdf {render template: 'todo_lists/reporte.html.erb', pdf: 'reporte', layout: 'pdf.html'}
    end
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)
    @todo_list.user = current_user
    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/controllers/todo_tasks_controller.rb
class TodoTasksController < ApplicationController
  before_action :authenticate_user!, only: [:new]

  before_action :set_todo_list

  def new
    @todo_task = TodoTask.new
  end

  def show
  end

  def create
    SendMailJob.perform_later
    @todo_task = @todo_list.todo_tasks.create(todo_task_params)
    redirect_to @todo_list
  end

  def update
    @todo_task = @todo_list.todo_tasks.find(params[:id])
    if @todo_task.update(todo_task_params)
      flash[:success] = "Todo List item was deleted."
    else
      flash[:error] = "Todo List item could not be deleted."
    end
    redirect_to @todo_list
  end


  def destroy
    @todo_task = TodoTask.find(params[:id])
    if @todo_task.destroy
      flash[:success] = "Todo List item was deleted."
    else
      flash[:error] = "Todo List item could not be deleted."
    end
    redirect_to @todo_list
  end

  def complete
   @todo_task.update_attribute(:completed_at, Time.now)
   redirect_to @todo_list, notice: "Todo task completed"
  end

  private

  def set_todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
    @todo_task = params[:id] ? TodoTask.find(params[:id]) : TodoTask.new
  end

  def todo_task_params
    params[:todo_task].permit(:content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/send_helper.rb
module SendHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/todo_tasks_helper.rb
module TodoTasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeviseApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <%= render "shared/navigation" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>
  <div class="container-fluid">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>

  <div class="container-fluid">
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>

</body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title></title>
    <meta charset= "utf-8">
  </head>

  <body>
      <%= yield %>
  </body>

</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/send/index.html.erb
<h1>Send#index</h1>
<p>Find me in app/views/send/index.html.erb</p>

<h1>Contacto</h1>
<%= flash[:notice] %>
<%= form_tag send_path,method: :post do %>
<%= label_tag :name,"Nombre" %><br/>
<%= text_field_tag :name %> <br/>
<%= label_tag :email, "Email" %> <br/>
<%= text_field_tag :email %> <br/>
<%= label_tag :subject, "Asunto" %> <br/>
<%= text_field_tag :subject %> <br/>
<%= label_tag :content, "Contenido" %><br/>
<%= text_area_tag :content %> <br/>
<%= submit_tag "Enviar" %>
<% end %>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Tutsplus Devise', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= current_user.username %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list, local: true) do |form| %>
  <% if todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :todo_list_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :todo_list_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing Todo List</h1>

<%= render 'form', todo_list: @todo_list %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todo Lists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_lists.each do |todo_list| %>
      <tr>
        <td><%= todo_list.title %></td>
        <td><%= todo_list.description %></td>
        <td><%= link_to 'Show', todo_list %></td>
        <td><%= link_to 'Edit', edit_todo_list_path(todo_list) %></td>
        <td><%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo List', new_todo_list_path %>
<%= link_to 'CSV', todo_lists_path(format: :csv) %>
<%= link_to 'Export PDF', todo_lists_path(format: :pdf)%>

app/views/todo_lists/new.html.erb
<h1>New Todo List</h1>

<%= render 'form', todo_list: @todo_list %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/reporte.html.erb
<div >
    <h1 >List and Tasks</h1>
<table >
    <thead>
        <tr>
            <th>title</th>
            <th>Description</th>
            <th>Task</th>
        </tr>
        <tbody>
            <% @todo_lists.all_todo_list_task.each do |todo_list| %>
                <tr>
                     <td><%= todo_list.title %></td>
                     <td><%= todo_list.description %></td>
                         <td><%= todo_list.task %></td>
                </tr>
            <%end%>

        </tbody>
    </thead>
</table>
</div>

app/views/todo_lists/reporte.pdf.erb
<div >
    <h1 >List and Tasks</h1>
<table >
    <thead>
        <tr>
            <th>title</th>
            <th>Description</th>
            <th>Task</th>
        </tr>
        <tbody>
            <% @todo_lists.all_todo_list_task.each do |todo_list| %>
                <tr>
                     <td><%= todo_list.title %></td>
                     <td><%= todo_list.description %></td>
                         <td><%= todo_list.task %></td>
                </tr>
            <%end%>

        </tbody>
    </thead>
</table>
</div>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo_list.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todo_list.description %>
</p>

<%= link_to 'Edit', edit_todo_list_path(@todo_list) %>

<div id="todo_tasks_wrapper">
  <%= render @todo_list.todo_tasks %>
</div>

<%= link_to 'Back', todo_lists_path %> |
<%= link_to 'New Task', new_todo_list_todo_task_path(@todo_list) %>

app/views/todo_tasks/_form.html.erb
<%= form_for([@todo_list, @todo_task]) do |form| %>
  <%= form.label :Tasks %>
  <%= form.text_field :content, id: :todo_task_content, placeholder: "New Task"%>
  <%= form.submit %>
<% end %>

app/views/todo_tasks/_todo_task.html.erb
<div class="row clearfix">
 <% if todo_task.completed? %>
  <div class="todo_task">
   <p style="opacity: 0.4;"><strike><%= todo_task.content %></strike></p>
  </div>
  <div class="complete">
   <%= link_to "Mark as Complete", complete_todo_list_todo_task_path(@todo_list, todo_task.id), method: :patch %> |
   <%= link_to "Delete", todo_list_todo_task_path(@todo_list, todo_task.id), method: :delete, data: { confirm: "Are you sure?" } %>
  </div>
  <% else %>
  <div class="todo_item">
   <p><%= todo_task.content %></p>
  </div>
  <div class="trash">
    <%= link_to "Mark as Complete", complete_todo_list_todo_task_path(@todo_list, todo_task.id), method: :patch %> |
    <%= link_to "Delete", todo_list_todo_task_path(@todo_list, todo_task.id), method: :delete, data: { confirm: "Are you sure?" } %> |
    <%= link_to "Edit",   edit_todo_list_todo_task_path(@todo_list, todo_task)%>
  </div>
 <% end %>
</div>

app/views/todo_tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', todo_task: @todo_task %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_tasks/new.html.erb
<h1>New Todo List</h1>

<%= render 'form', todo_task: @todo_task %>

<%= link_to 'Back', todo_lists_path %>